<?php

use Illuminate\Database\Seeder;

class AddressesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('addresses')->delete();
        
        \DB::table('addresses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 2,
                'city' => NULL,
                'city_id' => 941,
                'address' => 'www',
                'number' => NULL,
                'cp' => '6507',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 1,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-04-12 13:42:06',
                'updated_at' => '2021-04-12 13:42:06',
                'between_streets' => 'www',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 2,
                'city' => NULL,
                'city_id' => 2780,
                'address' => 'FRAY LUIS BELTRAN 623',
                'number' => NULL,
                'cp' => '1842',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 2,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-04-20 06:45:10',
                'updated_at' => '2021-04-20 06:45:10',
                'between_streets' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 2,
                'city' => NULL,
                'city_id' => 1290,
                'address' => 'SAN MARTIN 1333',
                'number' => NULL,
                'cp' => '1814',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 3,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-04-20 06:46:23',
                'updated_at' => '2021-04-20 06:46:23',
                'between_streets' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 1,
                'city' => NULL,
                'city_id' => 1291,
                'address' => 'SAN MARTIN 1333',
                'number' => '1333',
                'cp' => '1814',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 1,
                'addressable_type' => 'App\\Src\\Models\\Provider',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-04-20 13:07:20',
                'updated_at' => '2021-04-20 13:07:20',
                'between_streets' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 2,
                'city' => NULL,
                'city_id' => 1290,
                'address' => '25 DE MAYO 266',
                'number' => NULL,
                'cp' => '1814',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 5,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-04-20 20:40:14',
                'updated_at' => '2021-04-20 20:40:14',
                'between_streets' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 1,
                'city' => NULL,
                'city_id' => 1291,
                'address' => 'KENNEDY 160',
                'number' => '160',
                'cp' => '1814',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 2,
                'addressable_type' => 'App\\Src\\Models\\Provider',
                'type_id' => 1,
                'obs' => 'bn',
                'status_id' => 1,
                'created_at' => '2021-05-10 23:03:36',
                'updated_at' => '2021-05-10 23:03:36',
                'between_streets' => 'bnbnbn',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 2,
                'city' => NULL,
                'city_id' => 882,
                'address' => 'ttttttttt',
                'number' => NULL,
                'cp' => '1874',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 4,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-05-13 20:06:46',
                'updated_at' => '2021-05-13 20:06:46',
                'between_streets' => 'ttttt',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 2,
                'city' => NULL,
                'city_id' => 22740,
                'address' => 'AV. DE LOS LAGOS - LOTE 505 BARRIO ALISO 5300',
                'number' => '20135520773',
                'cp' => '1670',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 6,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-05-13 20:19:13',
                'updated_at' => '2021-05-13 20:19:13',
                'between_streets' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 1,
                'city' => NULL,
                'city_id' => 9060,
                'address' => 'FRAY LUIS BELTRAN 623',
                'number' => '623',
                'cp' => '1842',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 3,
                'addressable_type' => 'App\\Src\\Models\\Provider',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-05-14 12:35:52',
                'updated_at' => '2021-05-14 12:35:52',
                'between_streets' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 2,
                'city' => NULL,
                'city_id' => 12447,
                'address' => 'DIEGO LAURE 337',
                'number' => NULL,
                'cp' => '1804',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 7,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-05-18 02:44:59',
                'updated_at' => '2021-05-18 02:44:59',
                'between_streets' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 1,
                'city' => NULL,
                'city_id' => 23366,
                'address' => 'GUEMES, MACACHA,BOULEVARD 515',
                'number' => NULL,
                'cp' => '1106',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 8,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-05-18 15:44:15',
                'updated_at' => '2021-05-18 15:44:15',
                'between_streets' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 2,
                'city' => NULL,
                'city_id' => 1291,
                'address' => 'sasasas',
                'number' => NULL,
                'cp' => '1814',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 9,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-05-18 16:17:16',
                'updated_at' => '2021-05-18 16:17:16',
                'between_streets' => 'asas',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 2,
                'city' => NULL,
                'city_id' => 12486,
                'address' => 'AV. JUAN MANUEL DE ROSAS 161',
                'number' => '20261694086',
                'cp' => '1708',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 10,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-05-19 18:27:20',
                'updated_at' => '2021-05-19 18:27:20',
                'between_streets' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'code' => NULL,
                'country_id' => 1,
                'province_id' => 2,
                'city' => NULL,
                'city_id' => 12588,
                'address' => 'PEDRO MORAN 1264',
                'number' => NULL,
                'cp' => '1888',
                'message' => NULL,
                'geocoder' => NULL,
                'addressable_id' => 28,
                'addressable_type' => 'App\\Src\\Models\\Customer',
                'type_id' => 1,
                'obs' => NULL,
                'status_id' => 1,
                'created_at' => '2021-06-08 17:56:35',
                'updated_at' => '2021-06-08 17:56:35',
                'between_streets' => NULL,
            ),
        ));
        
        
    }
}