<?php

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'BARRUETA DIEGO ADRIAN | Test Test',
                'number' => '20227339730',
                'inscription_id' => 5,
                'address_id' => NULL,
                'purchaser_document_id' => 26,
                'datos_generales' => NULL,
                'regimen_general' => NULL,
                'monotributo' => NULL,
                'error_constancia' => NULL,
                'contact' => NULL,
                'afip_data' => '{"metadata": {"servidor": "linux11e", "fechaHora": "2021-05-04T23:55:19.013-03:00"}, "errorConstancia": {"error": "La clave ingresada no es una CUIT", "nombre": "DIEGO ADRIAN", "apellido": "BARRUETA", "idPersona": 20227339730}}',
                'created_at' => '2021-04-09 15:45:06',
                'updated_at' => '2021-05-05 02:55:19',
                'cell_phone' => NULL,
                'phone_1' => '01 1111-1111',
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => 'ttest.3xdg9rv+2-ogq2dqmjugmztqmzv@mail.mercadolibre.com',
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => '727194985',
                'meli_nick' => 'TETE6447876',
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'SEIDEM MAGALI RITA',
                'number' => '27341817876',
                'inscription_id' => 6,
                'address_id' => 2,
                'purchaser_document_id' => 25,
                'datos_generales' => '{"nombre": "MAGALI RITA", "apellido": "SEIDEM", "idPersona": 27341817876, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1842", "direccion": "FRAY LUIS BELTRAN 623", "localidad": "MONTE GRANDE", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}',
                'regimen_general' => NULL,
                'monotributo' => '{"impuesto": {"periodo": 201701, "idImpuesto": 20, "descripcionImpuesto": "MONOTRIBUTO"}, "categoriaMonotributo": {"periodo": 202002, "idImpuesto": 20, "idCategoria": 41, "descripcionCategoria": "G LOCACIONES DE SERVICIO"}, "actividadMonotributista": {"orden": 1, "periodo": 201709, "idActividad": 749009, "nomenclador": 883, "descripcionActividad": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS N.C.P."}}',
                'error_constancia' => NULL,
                'contact' => NULL,
                'afip_data' => '{"metadata": {"servidor": "linux11f", "fechaHora": "2021-04-20T03:45:10.657-03:00"}, "datosGenerales": {"nombre": "MAGALI RITA", "apellido": "SEIDEM", "idPersona": 27341817876, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1842", "direccion": "FRAY LUIS BELTRAN 623", "localidad": "MONTE GRANDE", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}, "datosMonotributo": {"impuesto": {"periodo": 201701, "idImpuesto": 20, "descripcionImpuesto": "MONOTRIBUTO"}, "categoriaMonotributo": {"periodo": 202002, "idImpuesto": 20, "idCategoria": 41, "descripcionCategoria": "G LOCACIONES DE SERVICIO"}, "actividadMonotributista": {"orden": 1, "periodo": 201709, "idActividad": 749009, "nomenclador": 883, "descripcionActividad": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS N.C.P."}}}',
                'created_at' => '2021-04-20 06:45:10',
                'updated_at' => '2021-04-20 06:45:10',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => NULL,
                'meli_nick' => NULL,
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'MENCONI ORLANDO DIONISIO',
                'number' => '20008721123',
                'inscription_id' => 1,
                'address_id' => 3,
                'purchaser_document_id' => 25,
                'datos_generales' => '{"nombre": "ORLANDO DIONISIO", "apellido": "MENCONI", "idPersona": 20008721123, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1814", "direccion": "SAN MARTIN 1333", "localidad": "CAÑUELAS", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}',
                'regimen_general' => '{"regimen": [{"periodo": 201105, "idRegimen": 78, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "ENAJENACION DE BIENES MUEBLES Y BIENES DE CAMBIO"}, {"periodo": 201105, "idRegimen": 94, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "REG.RET.A LAS GANANCIAS - LOCACIONES DE OBRAS Y/O SERVICIOS, NO EJECUTADOS EN RELACION DE DEPENDENCIA, QUE NO SE ENCUENTREN TAXATIVAMENTE MENCIONADOS EN LOS INCISOS I Y J."}, {"periodo": 200009, "idRegimen": 116, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "HONORARIOS DE DIRECTOR DE S.A., FIDUCIARIO, INTEGRANTE DE CONSEJOS DE VIGILANCIA, Y SOCIOS ADMINISTRADORES DE S.R.L., EN COMANDITA SIMPLE Y POR ACCIONES. PROFESIONALES LIBERALES, OFICIOS, ALBACEA, SINDICO, MANDATARIO, GESTOR DE NEGOCIO."}, {"periodo": 201211, "idRegimen": 742, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "EMPRESAS DE SERVICIOS EVENTUALES"}, {"periodo": 201709, "idRegimen": 754, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "RETENCION CONTRIBUCIONES PATRONALES PRESTACION SERVICIOS DE INVESTIGACIÓN Y SEGURIDAD"}, {"periodo": 201103, "idRegimen": 280, "idImpuesto": 767, "tipoRegimen": "RETENCION", "descripcionRegimen": "PAGO DE HONORARIOS PROFESIONALES"}], "impuesto": [{"periodo": 190101, "idImpuesto": 11, "descripcionImpuesto": "GANANCIAS PERSONAS FISICAS"}, {"periodo": 199206, "idImpuesto": 30, "descripcionImpuesto": "IVA"}, {"periodo": 200009, "idImpuesto": 217, "descripcionImpuesto": "SICORE-IMPTO.A LAS GANANCIAS"}, {"periodo": 195003, "idImpuesto": 301, "descripcionImpuesto": "EMPLEADOR-APORTES SEG. SOCIAL"}, {"periodo": 201211, "idImpuesto": 353, "descripcionImpuesto": "RETENCIONES CONTRIB.SEG.SOCIAL"}, {"periodo": 201103, "idImpuesto": 767, "descripcionImpuesto": "SICORE - RETENCIONES Y PERCEPC"}], "actividad": {"orden": 1, "periodo": 201311, "idActividad": 492240, "nomenclador": 883, "descripcionActividad": "SERVICIO DE TRANSPORTE POR CAMIÓN CISTERNA"}}',
                'monotributo' => NULL,
                'error_constancia' => NULL,
                'contact' => NULL,
                'afip_data' => '{"metadata": {"servidor": "linux11f", "fechaHora": "2021-04-20T03:46:22.986-03:00"}, "datosGenerales": {"nombre": "ORLANDO DIONISIO", "apellido": "MENCONI", "idPersona": 20008721123, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1814", "direccion": "SAN MARTIN 1333", "localidad": "CAÑUELAS", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}, "datosRegimenGeneral": {"regimen": [{"periodo": 201105, "idRegimen": 78, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "ENAJENACION DE BIENES MUEBLES Y BIENES DE CAMBIO"}, {"periodo": 201105, "idRegimen": 94, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "REG.RET.A LAS GANANCIAS - LOCACIONES DE OBRAS Y/O SERVICIOS, NO EJECUTADOS EN RELACION DE DEPENDENCIA, QUE NO SE ENCUENTREN TAXATIVAMENTE MENCIONADOS EN LOS INCISOS I Y J."}, {"periodo": 200009, "idRegimen": 116, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "HONORARIOS DE DIRECTOR DE S.A., FIDUCIARIO, INTEGRANTE DE CONSEJOS DE VIGILANCIA, Y SOCIOS ADMINISTRADORES DE S.R.L., EN COMANDITA SIMPLE Y POR ACCIONES. PROFESIONALES LIBERALES, OFICIOS, ALBACEA, SINDICO, MANDATARIO, GESTOR DE NEGOCIO."}, {"periodo": 201211, "idRegimen": 742, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "EMPRESAS DE SERVICIOS EVENTUALES"}, {"periodo": 201709, "idRegimen": 754, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "RETENCION CONTRIBUCIONES PATRONALES PRESTACION SERVICIOS DE INVESTIGACIÓN Y SEGURIDAD"}, {"periodo": 201103, "idRegimen": 280, "idImpuesto": 767, "tipoRegimen": "RETENCION", "descripcionRegimen": "PAGO DE HONORARIOS PROFESIONALES"}], "impuesto": [{"periodo": 190101, "idImpuesto": 11, "descripcionImpuesto": "GANANCIAS PERSONAS FISICAS"}, {"periodo": 199206, "idImpuesto": 30, "descripcionImpuesto": "IVA"}, {"periodo": 200009, "idImpuesto": 217, "descripcionImpuesto": "SICORE-IMPTO.A LAS GANANCIAS"}, {"periodo": 195003, "idImpuesto": 301, "descripcionImpuesto": "EMPLEADOR-APORTES SEG. SOCIAL"}, {"periodo": 201211, "idImpuesto": 353, "descripcionImpuesto": "RETENCIONES CONTRIB.SEG.SOCIAL"}, {"periodo": 201103, "idImpuesto": 767, "descripcionImpuesto": "SICORE - RETENCIONES Y PERCEPC"}], "actividad": {"orden": 1, "periodo": 201311, "idActividad": 492240, "nomenclador": 883, "descripcionActividad": "SERVICIO DE TRANSPORTE POR CAMIÓN CISTERNA"}}}',
                'created_at' => '2021-04-20 06:46:23',
                'updated_at' => '2021-04-20 06:46:23',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => NULL,
                'meli_nick' => NULL,
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'BARRUETA DIEGO ADRIAN',
                'number' => '20227339730',
                'inscription_id' => 5,
                'address_id' => NULL,
                'purchaser_document_id' => 26,
                'datos_generales' => NULL,
                'regimen_general' => NULL,
                'monotributo' => NULL,
                'error_constancia' => NULL,
                'contact' => NULL,
                'afip_data' => '{"metadata": {"servidor": "linux11c", "fechaHora": "2021-04-20T15:20:03.404-03:00"}, "errorConstancia": {"error": "La clave ingresada no es una CUIT", "nombre": "DIEGO ADRIAN", "apellido": "BARRUETA", "idPersona": 20227339730}}',
                'created_at' => '2021-04-20 18:20:03',
                'updated_at' => '2021-04-20 18:20:03',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => NULL,
                'meli_nick' => NULL,
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'MENCONI CESAR ORLANDO',
                'number' => '20083103818',
                'inscription_id' => 1,
                'address_id' => 5,
                'purchaser_document_id' => 25,
                'datos_generales' => '{"nombre": "CESAR ORLANDO", "apellido": "MENCONI", "idPersona": 20083103818, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1814", "direccion": "25 DE MAYO 266", "localidad": "CAÑUELAS", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}',
                'regimen_general' => '{"impuesto": [{"periodo": 200706, "idImpuesto": 11, "descripcionImpuesto": "GANANCIAS PERSONAS FISICAS"}, {"periodo": 200706, "idImpuesto": 30, "descripcionImpuesto": "IVA"}, {"periodo": 200704, "idImpuesto": 308, "descripcionImpuesto": "APORTES SEG.SOCIAL AUTONOMOS"}], "actividad": {"orden": 1, "periodo": 201311, "idActividad": 829900, "nomenclador": 883, "descripcionActividad": "SERVICIOS EMPRESARIALES N.C.P."}, "categoriaAutonomo": {"periodo": 201510, "idImpuesto": 308, "idCategoria": 501, "descripcionCategoria": "CAT I JUBILADO"}}',
                'monotributo' => NULL,
                'error_constancia' => NULL,
                'contact' => NULL,
                'afip_data' => '{"metadata": {"servidor": "linux11e", "fechaHora": "2021-04-20T17:40:14.341-03:00"}, "datosGenerales": {"nombre": "CESAR ORLANDO", "apellido": "MENCONI", "idPersona": 20083103818, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1814", "direccion": "25 DE MAYO 266", "localidad": "CAÑUELAS", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}, "datosRegimenGeneral": {"impuesto": [{"periodo": 200706, "idImpuesto": 11, "descripcionImpuesto": "GANANCIAS PERSONAS FISICAS"}, {"periodo": 200706, "idImpuesto": 30, "descripcionImpuesto": "IVA"}, {"periodo": 200704, "idImpuesto": 308, "descripcionImpuesto": "APORTES SEG.SOCIAL AUTONOMOS"}], "actividad": {"orden": 1, "periodo": 201311, "idActividad": 829900, "nomenclador": 883, "descripcionActividad": "SERVICIOS EMPRESARIALES N.C.P."}, "categoriaAutonomo": {"periodo": 201510, "idImpuesto": 308, "idCategoria": 501, "descripcionCategoria": "CAT I JUBILADO"}}}',
                'created_at' => '2021-04-20 20:40:14',
                'updated_at' => '2021-04-20 20:40:14',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => NULL,
                'meli_nick' => NULL,
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'ARRICAR AXEL CLAUDIO',
                'number' => '20135520773',
                'inscription_id' => 1,
                'address_id' => NULL,
                'purchaser_document_id' => 25,
            'datos_generales' => '{"nombre": "AXEL CLAUDIO", "apellido": "ARRICAR", "idPersona": 20135520773, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1670", "direccion": "AV. DE LOS LAGOS - LOTE 505 BARRIO ALISO 5300", "localidad": "NORDELTA (TIGRE)", "idProvincia": 1, "datoAdicional": "LOS ALISOS -NORDELTA", "tipoDomicilio": "FISCAL", "tipoDatoAdicional": "BARRIO", "descripcionProvincia": "BUENOS AIRES"}}',
                'regimen_general' => '{"actividad": [{"orden": 2, "periodo": 201707, "idActividad": 681099, "nomenclador": 883, "descripcionActividad": "SERVICIOS INMOBILIARIOS REALIZADOS POR CUENTA PROPIA, CON BIENES RURALES PROPIOS O ARRENDADOS N.C.P."}, {"orden": 1, "periodo": 201311, "idActividad": 692000, "nomenclador": 883, "descripcionActividad": "SERVICIOS DE CONTABILIDAD, AUDITORÍA Y ASESORÍA FISCAL"}]}',
                'monotributo' => '{"impuesto": {"periodo": 202008, "idImpuesto": 20, "descripcionImpuesto": "MONOTRIBUTO"}, "categoriaMonotributo": {"periodo": 202008, "idImpuesto": 20, "idCategoria": 39, "descripcionCategoria": "E LOCACIONES DE SERVICIO"}, "actividadMonotributista": {"orden": 1, "periodo": 201311, "idActividad": 692000, "nomenclador": 883, "descripcionActividad": "SERVICIOS DE CONTABILIDAD, AUDITORÍA Y ASESORÍA FISCAL"}}',
                'error_constancia' => NULL,
                'contact' => NULL,
            'afip_data' => '{"metadata": {"servidor": "linux11d", "fechaHora": "2021-05-13T17:18:14.341-03:00"}, "datosGenerales": {"nombre": "AXEL CLAUDIO", "apellido": "ARRICAR", "idPersona": 20135520773, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1670", "direccion": "AV. DE LOS LAGOS - LOTE 505 BARRIO ALISO 5300", "localidad": "NORDELTA (TIGRE)", "idProvincia": 1, "datoAdicional": "LOS ALISOS -NORDELTA", "tipoDomicilio": "FISCAL", "tipoDatoAdicional": "BARRIO", "descripcionProvincia": "BUENOS AIRES"}}, "datosMonotributo": {"impuesto": {"periodo": 202008, "idImpuesto": 20, "descripcionImpuesto": "MONOTRIBUTO"}, "categoriaMonotributo": {"periodo": 202008, "idImpuesto": 20, "idCategoria": 39, "descripcionCategoria": "E LOCACIONES DE SERVICIO"}, "actividadMonotributista": {"orden": 1, "periodo": 201311, "idActividad": 692000, "nomenclador": 883, "descripcionActividad": "SERVICIOS DE CONTABILIDAD, AUDITORÍA Y ASESORÍA FISCAL"}}, "datosRegimenGeneral": {"actividad": [{"orden": 2, "periodo": 201707, "idActividad": 681099, "nomenclador": 883, "descripcionActividad": "SERVICIOS INMOBILIARIOS REALIZADOS POR CUENTA PROPIA, CON BIENES RURALES PROPIOS O ARRENDADOS N.C.P."}, {"orden": 1, "periodo": 201311, "idActividad": 692000, "nomenclador": 883, "descripcionActividad": "SERVICIOS DE CONTABILIDAD, AUDITORÍA Y ASESORÍA FISCAL"}]}}',
                'created_at' => '2021-05-13 20:19:13',
                'updated_at' => '2021-05-13 20:19:13',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => NULL,
                'meli_nick' => NULL,
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'CALLAO MARCELO JORGE',
                'number' => '23263268709',
                'inscription_id' => NULL,
                'address_id' => 10,
                'purchaser_document_id' => 25,
                'datos_generales' => '{"nombre": "MARCELO JORGE", "apellido": "CALLAO", "idPersona": 23263268709, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1804", "direccion": "DIEGO LAURE 337", "localidad": "Carlos Spegazzini", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}',
                'regimen_general' => NULL,
                'monotributo' => NULL,
                'error_constancia' => NULL,
                'contact' => NULL,
                'afip_data' => '{"metadata": {"servidor": "linux11b", "fechaHora": "2021-05-17T23:44:59.036-03:00"}, "datosGenerales": {"nombre": "MARCELO JORGE", "apellido": "CALLAO", "idPersona": 23263268709, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1804", "direccion": "DIEGO LAURE 337", "localidad": "Carlos Spegazzini", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}}',
                'created_at' => '2021-05-18 02:44:59',
                'updated_at' => '2021-05-18 02:44:59',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => NULL,
                'meli_nick' => NULL,
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'YPF SOCIEDAD ANONIMA',
                'number' => '30546689979',
                'inscription_id' => 1,
                'address_id' => 11,
                'purchaser_document_id' => 25,
                'datos_generales' => '{"idPersona": 30546689979, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "razonSocial": "YPF SOCIEDAD ANONIMA", "tipoPersona": "JURIDICA", "domicilioFiscal": {"codPostal": "1106", "direccion": "GUEMES, MACACHA,BOULEVARD 515", "idProvincia": 0, "tipoDomicilio": "FISCAL", "descripcionProvincia": "CIUDAD AUTONOMA BUENOS AIRES"}, "fechaContratoSocial": "1901-01-01T12:00:00-04:16"}',
            'regimen_general' => '{"regimen": [{"periodo": 201912, "idRegimen": 209, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "INGRESOS OBTENIDOS POR LA COMERCIALIZACION DE ESPACIOS PUBLICITARIOS - ART. 8, INC. B) Y ART. 28 INC. G) DE LA LEY DE IVA."}, {"periodo": 201912, "idRegimen": 210, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "SERVICIOS DE TRANSPORTE DE PASAJEROS, TERRESTRES, ACUATICOS O AEREOS - ART. 8 INC.B) Y ART. 28 INC. H) DE LA LEY DE IVA."}, {"periodo": 201912, "idRegimen": 211, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "SERVICIOS DE ASISTENCIA SANITARIA MEDICA Y PARAMEDICA - ART. 8 INC. B) Y ART 28 INC. I) DE LA LEY DE IVA."}, {"periodo": 202001, "idRegimen": 212, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "LOCACIONES O PRESTACIONES DE SERVICIOS, NO COMPRENDIDAS EN EL ART. 8, INC. B)."}, {"periodo": 202001, "idRegimen": 214, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "COMPRAVENTA DE COSAS MUEBLES Y LOCACIONES COMPRENDIDAS EN EL INCISO C) DEL ARTICULO 3° DE LA LEY DE IVA - ART. 8>, INC. A)"}, {"periodo": 202003, "idRegimen": 217, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRABAJOS SOBRE INMUEBLE AJENO - ART. 8 INC. B) Y ART. 28 INC. C) DE LA LEY DE IVA"}, {"periodo": 201912, "idRegimen": 499, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "FACTURA M-IVA-EMISION DE COMPROBANTES CON DISCRIMINACION DEL GRAVAMEN"}, {"periodo": 201912, "idRegimen": 777, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "IVA -RÉGIMEN DE RETENCIÓN A SUJETOS ADHERIDOS AL RÉGIMEN SIMPLIFICADO PARA PEQUEÑOS CONTRIBUYENTES."}, {"periodo": 200001, "idRegimen": 19, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "INTERESES POR OPERACIONES REALIZADAS EN ENTIDADES FINANCIERAS-LEY N° 21.526"}, {"periodo": 200902, "idRegimen": 30, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "ALQUILERES O ARRENDAMIENTOS DE BIENES MUEBLES"}, {"periodo": 200902, "idRegimen": 31, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "BIENES INMUEBLES URBANOS INCLUÍDOS LOS EFECTUADOS BAJO MODALIDAD DE LEASING-INCLUYE SUBURBANOS."}, {"periodo": 200902, "idRegimen": 32, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "BIENES INMUEBLES RURALES, INCLUÍDOS LOS EFECTUADOS BAJO MODALIDAD DE LEASING-INCLUYE SUBRURALES-."}, {"periodo": 200001, "idRegimen": 43, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "INTERES ACCIONARIO, EXCEDENTES Y RETORNOS DISTRIBUIDOS ENTRE ASOCIADOS,COOPERATIVAS- EXCEPTO CONSUMO"}, {"periodo": 200001, "idRegimen": 51, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "OBLIGACIONES DE NO HACER, O POR ABANDONO O POR NO EJERCICIO DE UNA ACTIVIDAD"}, {"periodo": 200001, "idRegimen": 78, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "ENAJENACION DE BIENES MUEBLES Y BIENES DE CAMBIO"}, {"periodo": 200001, "idRegimen": 94, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "REG.RET.A LAS GANANCIAS - LOCACIONES DE OBRAS Y/O SERVICIOS, NO EJECUTADOS EN RELACION DE DEPENDENCIA, QUE NO SE ENCUENTREN TAXATIVAMENTE MENCIONADOS EN LOS INCISOS I Y J."}, {"periodo": 200001, "idRegimen": 116, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "HONORARIOS DE DIRECTOR DE S.A., FIDUCIARIO, INTEGRANTE DE CONSEJOS DE VIGILANCIA, Y SOCIOS ADMINISTRADORES DE S.R.L., EN COMANDITA SIMPLE Y POR ACCIONES. PROFESIONALES LIBERALES, OFICIOS, ALBACEA, SINDICO, MANDATARIO, GESTOR DE NEGOCIO."}, {"periodo": 200001, "idRegimen": 124, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "CORREDORES, VIAJANTES, Y DESPACHANTES DE ADUANA"}, {"periodo": 200904, "idRegimen": 775, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "GANANCIAS - RÉGIMEN DE RETENCIÓN A SUJETOS ADHERIDOS AL RÉGIMEN SIMPLIFICADO PARA PEQUEÑOS CONTRIBUYENTES."}, {"periodo": 201610, "idRegimen": 164, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "DERECHOS DE AUTOR - EXCEPTO SOFTWARE"}, {"periodo": 201503, "idRegimen": 171, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "OTRAS GANANCIAS NO PREVISTAS"}, {"periodo": 201503, "idRegimen": 765, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSFERENCIA DE TECNOLOGIA-INC A) PTO 1 ART 93 LIG-MARCAS Y PATENTES, Y DEMAS PRESTACIONES DE TECNOLOGIA INC A) PTO 2 ART 93 LIG, EN TODOS LOS CASOS EN QUE NO CUMPLEN LOS REQUIS.LEGALES PREVISTOS POR LA AUTORIDAD DE APLICACION (LEY TRANSF TECNO.)"}, {"periodo": 201503, "idRegimen": 808, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSPORTE MARITIMO INTERNACIONAL - COMPAÑIAS NO CONSTITUIDAS EN EL PASI - FLETES POR PASAJES Y CARGAS"}, {"periodo": 201503, "idRegimen": 809, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSPORTE AEREO INTERNACIONAL - COMPAÑIAS NO CONSTITUIDAS EN EL PAIS - FLETES POR PASAJES Y CARGAS"}, {"periodo": 201503, "idRegimen": 810, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSPORTE TERRESTRE INTERNACIONAL - COMPAÑIAS NO CONSTITUIDAS EN EL PAIS - FLETES POR PASAJES Y CARGAS"}, {"periodo": 201801, "idRegimen": 819, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "INTERESES POR PRESTAMOS OBTENIDOS EN EL EXTERIOR- ART. 93 INCISO C) PUNTO 2, DE LA LIG"}, {"periodo": 201503, "idRegimen": 820, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "RETRIBUCIONES POR SERVICIOS PERSONALES INDEPENDIENTES"}, {"periodo": 201503, "idRegimen": 821, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "LOCACION DE COSAS MUEBLES DEL PAIS, EFECTUADAS POR LOCADORES DEL EXTERIOR"}, {"periodo": 201507, "idRegimen": 860, "idImpuesto": 218, "tipoRegimen": "PAGO UNICO Y DEFINITIVO", "descripcionRegimen": "DIV. O UTILIDADES EN DINERO O ESPECIE - EXCEPTO ACCIONES O CUOTAS PARTES - LEY 26893"}, {"periodo": 201503, "idRegimen": 894, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSPORTE INTERNACIONAL - OPERACIONES CON CONTENEDORES"}, {"periodo": 201503, "idRegimen": 897, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSPORTE INTERNACIONAL - ARMADORES EXTRANJEROS - FLETAMENTOS A TIEMPO"}, {"periodo": 201503, "idRegimen": 901, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSMISIONES DE RADIO Y TELEVISION EMITIDAS DESDE EL EXTERIOR, SERVICIO DE TELEX, TELEFACSIMIL O SIMILARES, TRANSMITIDOS DESDE EL EXTERIOR Y TODO OTRO MEDIO EXTRANJERO DE PROYECCION, REPRODUCCION, TRANSMISION O DIFUSION DE IMAGENES O SONIDO"}, {"periodo": 201503, "idRegimen": 902, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSFERENCIA DE TECNOLOGIA - ASISTENCIA TECNICA, SERVICIOS DE INGENIERIA O CONSULTORIA NO OBTENIBLES EN EL PAIS INCLUIDAS EN EL INCISO A) PUNTO 1, DEL ART.93 DE LA LIG EXCEPTO SOFTWARE"}, {"periodo": 201503, "idRegimen": 903, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSFERENCIA DE TECNOLOGIA - MARCAS Y PATANTES Y DEMAS PRESENTACIONES DE TECNOLOGIA DEL INCISO A) PUNTO 2. DEL ART. 93 DE LA LIG -EXCEPTO SOFTWARE"}, {"periodo": 201503, "idRegimen": 904, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "INTERESES POR PRESTAMOS OBTENIDOS EN EL EXTERIOR - ART. 93 INCISO C) PUNTO 1, DE LA LIG"}, {"periodo": 200005, "idRegimen": 740, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "EMPRESAS CONSTRUCTORAS"}, {"periodo": 200005, "idRegimen": 742, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "EMPRESAS DE SERVICIOS EVENTUALES"}, {"periodo": 200312, "idRegimen": 748, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "RETENCIÓN DE PRESTADORES DE SERVICIOS DE LIMPIEZA DE INMUEBLES"}, {"periodo": 200502, "idRegimen": 754, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "RETENCION CONTRIBUCIONES PATRONALES PRESTACION SERVICIOS DE INVESTIGACIÓN Y SEGURIDAD"}, {"periodo": 201007, "idRegimen": 755, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "RETENCIÓN GENERAL DE CONTRIBUCIONES"}, {"periodo": 200808, "idRegimen": 254, "idImpuesto": 767, "tipoRegimen": "PERCEPCION", "descripcionRegimen": "PERCEPCIÓN RG 2459-CANJE GRANOS-SUJETO EN ESTADO 2 EN EL SISTEMA DE INFORMACIÓN SIMPLIFICADO AGRÍCOLA SISA"}, {"periodo": 200808, "idRegimen": 255, "idImpuesto": 767, "tipoRegimen": "PERCEPCION", "descripcionRegimen": "PERCEPCIÓN RG 2459-CANJE GRANOS-SUJETO EN ESTADO 3 EN EL SISTEMA DE INFORMACIÓN SIMPLIFICADO AGRÍCOLA SISA"}, {"periodo": 200001, "idRegimen": 493, "idImpuesto": 767, "tipoRegimen": "PERCEPCION", "descripcionRegimen": "REG.PER.AL VALOR AGREGADO - EMPRESAS PROVEEDORAS."}, {"periodo": 200904, "idRegimen": 777, "idImpuesto": 767, "tipoRegimen": "RETENCION", "descripcionRegimen": "IVA -RÉGIMEN DE RETENCIÓN A SUJETOS ADHERIDOS AL RÉGIMEN SIMPLIFICADO PARA PEQUEÑOS CONTRIBUYENTES."}, {"periodo": 201706, "idRegimen": 160, "idImpuesto": 787, "tipoRegimen": "RETENCION", "descripcionRegimen": "RENTAS DEL TRABAJO PERSONAL BAJO RELACIÓN DE DEPENDENCIA Y OTROS"}, {"periodo": 20070101, "idRegimen": 68, "idImpuesto": 103, "descripcionRegimen": "PARTICIPACIONES SOCIETARIAS"}, {"periodo": 20080603, "idRegimen": 71, "idImpuesto": 103, "descripcionRegimen": "CITI - VENTAS"}, {"periodo": 20050101, "idRegimen": 72, "idImpuesto": 103, "descripcionRegimen": "CITI - COMPRAS"}, {"periodo": 20040701, "idRegimen": 74, "idImpuesto": 103, "descripcionRegimen": "RANCHO - PRODUCTORES"}, {"periodo": 20100101, "idRegimen": 216, "idImpuesto": 103, "descripcionRegimen": "TARJETAS DE CREDITO"}, {"periodo": 20091201, "idRegimen": 255, "idImpuesto": 103, "descripcionRegimen": "PRESENTACION DE ESTADOS CONTABLES EN FORMATO PDF"}], "impuesto": [{"periodo": 198005, "idImpuesto": 10, "descripcionImpuesto": "GANANCIAS SOCIEDADES"}, {"periodo": 198903, "idImpuesto": 30, "descripcionImpuesto": "IVA"}, {"periodo": 200407, "idImpuesto": 103, "descripcionImpuesto": "REGIMENES DE INFORMACIÓN"}, {"periodo": 199206, "idImpuesto": 181, "descripcionImpuesto": "COMB LIQ L 23966 NAFTAS"}, {"periodo": 200305, "idImpuesto": 211, "descripcionImpuesto": "BP-ACCIONES O PARTICIPACIONES"}, {"periodo": 202002, "idImpuesto": 216, "descripcionImpuesto": "SIRE -  IVA"}, {"periodo": 200001, "idImpuesto": 217, "descripcionImpuesto": "SICORE-IMPTO.A LAS GANANCIAS"}, {"periodo": 201503, "idImpuesto": 218, "descripcionImpuesto": "IMP.A LAS GAN.- BENEF.DEL EXT."}, {"periodo": 200201, "idImpuesto": 228, "descripcionImpuesto": "FONDO HIDRIC DE INFRAESTRUCTUR"}, {"periodo": 200205, "idImpuesto": 229, "descripcionImpuesto": "RECARGO SOBRE EL GAS NATURAL"}, {"periodo": 200701, "idImpuesto": 240, "descripcionImpuesto": "NAFTA FONDO HIDRICO DE INFR."}, {"periodo": 192206, "idImpuesto": 301, "descripcionImpuesto": "EMPLEADOR-APORTES SEG. SOCIAL"}, {"periodo": 200005, "idImpuesto": 353, "descripcionImpuesto": "RETENCIONES CONTRIB.SEG.SOCIAL"}, {"periodo": 199807, "idImpuesto": 377, "descripcionImpuesto": "COM LIQ L.23966/24699 ART 2DOA"}, {"periodo": 199807, "idImpuesto": 395, "descripcionImpuesto": "COMB LIQ L 23966/24699 ART 2 B"}, {"periodo": 200506, "idImpuesto": 398, "descripcionImpuesto": "IMPUESTO S/GAS OIL"}, {"periodo": 200001, "idImpuesto": 767, "descripcionImpuesto": "SICORE - RETENCIONES Y PERCEPC"}, {"periodo": 201706, "idImpuesto": 787, "descripcionImpuesto": "RET ART 79 LEY GCIAS INC A,BYC"}, {"periodo": 201803, "idImpuesto": 1018, "descripcionImpuesto": "CO2 - NAFTAS"}, {"periodo": 201803, "idImpuesto": 1019, "descripcionImpuesto": "CO2-SOLV. AGUARRAS GASOL.NAF V"}, {"periodo": 201803, "idImpuesto": 1020, "descripcionImpuesto": "CO2 - GASOIL DIESELOIL Y KEROS"}, {"periodo": 201901, "idImpuesto": 1021, "descripcionImpuesto": "DIOXIDO DE CARBONO - FUEL OIL"}, {"periodo": 201901, "idImpuesto": 1022, "descripcionImpuesto": "CO2 - COQUE PETROL Y CARB MIN"}], "actividad": [{"orden": 1, "periodo": 201401, "idActividad": 61000, "nomenclador": 883, "descripcionActividad": "EXTRACCIÓN DE PETRÓLEO CRUDO"}, {"orden": 2, "periodo": 201401, "idActividad": 62000, "nomenclador": 883, "descripcionActividad": "EXTRACCIÓN DE GAS NATURAL"}, {"orden": 13, "periodo": 201902, "idActividad": 81300, "nomenclador": 883, "descripcionActividad": "EXTRACCIÓN DE ARENAS, CANTO RODADO Y TRITURADOS PÉTREOS"}, {"orden": 3, "periodo": 201401, "idActividad": 192000, "nomenclador": 883, "descripcionActividad": "FABRICACIÓN DE PRODUCTOS DE LA REFINACIÓN DEL PETRÓLEO"}, {"orden": 6, "periodo": 201401, "idActividad": 351110, "nomenclador": 883, "descripcionActividad": "GENERACIÓN DE ENERGÍA TÉRMICA CONVENCIONAL"}, {"orden": 8, "periodo": 201401, "idActividad": 461011, "nomenclador": 883, "descripcionActividad": "VENTA AL POR MAYOR EN COMISIÓN O CONSIGNACIÓN DE CEREALES (INCLUYE ARROZ), OLEAGINOSAS Y FORRAJERAS EXCEPTO SEMILLAS"}, {"orden": 9, "periodo": 201405, "idActividad": 473000, "nomenclador": 883, "descripcionActividad": "VENTA AL POR MENOR DE COMBUSTIBLE PARA VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"}, {"orden": 10, "periodo": 201509, "idActividad": 649210, "nomenclador": 883, "descripcionActividad": "ACTIVIDADES DE CRÉDITO PARA FINANCIAR OTRAS ACTIVIDADES ECONÓMICAS"}, {"orden": 12, "periodo": 201612, "idActividad": 649999, "nomenclador": 883, "descripcionActividad": "SERVICIOS DE FINANCIACIÓN Y ACTIVIDADES FINANCIERAS N.C.P."}, {"orden": 11, "periodo": 201612, "idActividad": 661121, "nomenclador": 883, "descripcionActividad": "SERVICIOS DE MERCADOS A TÉRMINO"}, {"orden": 7, "periodo": 201401, "idActividad": 681098, "nomenclador": 883, "descripcionActividad": "SERVICIOS INMOBILIARIOS REALIZADOS POR CUENTA PROPIA, CON BIENES URBANOS PROPIOS O ARRENDADOS N.C.P."}, {"orden": 5, "periodo": 201401, "idActividad": 681099, "nomenclador": 883, "descripcionActividad": "SERVICIOS INMOBILIARIOS REALIZADOS POR CUENTA PROPIA, CON BIENES RURALES PROPIOS O ARRENDADOS N.C.P."}, {"orden": 4, "periodo": 201401, "idActividad": 682099, "nomenclador": 883, "descripcionActividad": "SERVICIOS INMOBILIARIOS REALIZADOS A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA N.C.P."}]}',
                'monotributo' => NULL,
                'error_constancia' => NULL,
                'contact' => NULL,
            'afip_data' => '{"metadata": {"servidor": "linux11b", "fechaHora": "2021-05-18T12:44:14.484-03:00"}, "datosGenerales": {"idPersona": 30546689979, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "razonSocial": "YPF SOCIEDAD ANONIMA", "tipoPersona": "JURIDICA", "domicilioFiscal": {"codPostal": "1106", "direccion": "GUEMES, MACACHA,BOULEVARD 515", "idProvincia": 0, "tipoDomicilio": "FISCAL", "descripcionProvincia": "CIUDAD AUTONOMA BUENOS AIRES"}, "fechaContratoSocial": "1901-01-01T12:00:00-04:16"}, "datosRegimenGeneral": {"regimen": [{"periodo": 201912, "idRegimen": 209, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "INGRESOS OBTENIDOS POR LA COMERCIALIZACION DE ESPACIOS PUBLICITARIOS - ART. 8, INC. B) Y ART. 28 INC. G) DE LA LEY DE IVA."}, {"periodo": 201912, "idRegimen": 210, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "SERVICIOS DE TRANSPORTE DE PASAJEROS, TERRESTRES, ACUATICOS O AEREOS - ART. 8 INC.B) Y ART. 28 INC. H) DE LA LEY DE IVA."}, {"periodo": 201912, "idRegimen": 211, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "SERVICIOS DE ASISTENCIA SANITARIA MEDICA Y PARAMEDICA - ART. 8 INC. B) Y ART 28 INC. I) DE LA LEY DE IVA."}, {"periodo": 202001, "idRegimen": 212, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "LOCACIONES O PRESTACIONES DE SERVICIOS, NO COMPRENDIDAS EN EL ART. 8, INC. B)."}, {"periodo": 202001, "idRegimen": 214, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "COMPRAVENTA DE COSAS MUEBLES Y LOCACIONES COMPRENDIDAS EN EL INCISO C) DEL ARTICULO 3° DE LA LEY DE IVA - ART. 8>, INC. A)"}, {"periodo": 202003, "idRegimen": 217, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRABAJOS SOBRE INMUEBLE AJENO - ART. 8 INC. B) Y ART. 28 INC. C) DE LA LEY DE IVA"}, {"periodo": 201912, "idRegimen": 499, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "FACTURA M-IVA-EMISION DE COMPROBANTES CON DISCRIMINACION DEL GRAVAMEN"}, {"periodo": 201912, "idRegimen": 777, "idImpuesto": 216, "tipoRegimen": "RETENCION", "descripcionRegimen": "IVA -RÉGIMEN DE RETENCIÓN A SUJETOS ADHERIDOS AL RÉGIMEN SIMPLIFICADO PARA PEQUEÑOS CONTRIBUYENTES."}, {"periodo": 200001, "idRegimen": 19, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "INTERESES POR OPERACIONES REALIZADAS EN ENTIDADES FINANCIERAS-LEY N° 21.526"}, {"periodo": 200902, "idRegimen": 30, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "ALQUILERES O ARRENDAMIENTOS DE BIENES MUEBLES"}, {"periodo": 200902, "idRegimen": 31, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "BIENES INMUEBLES URBANOS INCLUÍDOS LOS EFECTUADOS BAJO MODALIDAD DE LEASING-INCLUYE SUBURBANOS."}, {"periodo": 200902, "idRegimen": 32, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "BIENES INMUEBLES RURALES, INCLUÍDOS LOS EFECTUADOS BAJO MODALIDAD DE LEASING-INCLUYE SUBRURALES-."}, {"periodo": 200001, "idRegimen": 43, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "INTERES ACCIONARIO, EXCEDENTES Y RETORNOS DISTRIBUIDOS ENTRE ASOCIADOS,COOPERATIVAS- EXCEPTO CONSUMO"}, {"periodo": 200001, "idRegimen": 51, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "OBLIGACIONES DE NO HACER, O POR ABANDONO O POR NO EJERCICIO DE UNA ACTIVIDAD"}, {"periodo": 200001, "idRegimen": 78, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "ENAJENACION DE BIENES MUEBLES Y BIENES DE CAMBIO"}, {"periodo": 200001, "idRegimen": 94, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "REG.RET.A LAS GANANCIAS - LOCACIONES DE OBRAS Y/O SERVICIOS, NO EJECUTADOS EN RELACION DE DEPENDENCIA, QUE NO SE ENCUENTREN TAXATIVAMENTE MENCIONADOS EN LOS INCISOS I Y J."}, {"periodo": 200001, "idRegimen": 116, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "HONORARIOS DE DIRECTOR DE S.A., FIDUCIARIO, INTEGRANTE DE CONSEJOS DE VIGILANCIA, Y SOCIOS ADMINISTRADORES DE S.R.L., EN COMANDITA SIMPLE Y POR ACCIONES. PROFESIONALES LIBERALES, OFICIOS, ALBACEA, SINDICO, MANDATARIO, GESTOR DE NEGOCIO."}, {"periodo": 200001, "idRegimen": 124, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "CORREDORES, VIAJANTES, Y DESPACHANTES DE ADUANA"}, {"periodo": 200904, "idRegimen": 775, "idImpuesto": 217, "tipoRegimen": "RETENCION", "descripcionRegimen": "GANANCIAS - RÉGIMEN DE RETENCIÓN A SUJETOS ADHERIDOS AL RÉGIMEN SIMPLIFICADO PARA PEQUEÑOS CONTRIBUYENTES."}, {"periodo": 201610, "idRegimen": 164, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "DERECHOS DE AUTOR - EXCEPTO SOFTWARE"}, {"periodo": 201503, "idRegimen": 171, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "OTRAS GANANCIAS NO PREVISTAS"}, {"periodo": 201503, "idRegimen": 765, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSFERENCIA DE TECNOLOGIA-INC A) PTO 1 ART 93 LIG-MARCAS Y PATENTES, Y DEMAS PRESTACIONES DE TECNOLOGIA INC A) PTO 2 ART 93 LIG, EN TODOS LOS CASOS EN QUE NO CUMPLEN LOS REQUIS.LEGALES PREVISTOS POR LA AUTORIDAD DE APLICACION (LEY TRANSF TECNO.)"}, {"periodo": 201503, "idRegimen": 808, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSPORTE MARITIMO INTERNACIONAL - COMPAÑIAS NO CONSTITUIDAS EN EL PASI - FLETES POR PASAJES Y CARGAS"}, {"periodo": 201503, "idRegimen": 809, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSPORTE AEREO INTERNACIONAL - COMPAÑIAS NO CONSTITUIDAS EN EL PAIS - FLETES POR PASAJES Y CARGAS"}, {"periodo": 201503, "idRegimen": 810, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSPORTE TERRESTRE INTERNACIONAL - COMPAÑIAS NO CONSTITUIDAS EN EL PAIS - FLETES POR PASAJES Y CARGAS"}, {"periodo": 201801, "idRegimen": 819, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "INTERESES POR PRESTAMOS OBTENIDOS EN EL EXTERIOR- ART. 93 INCISO C) PUNTO 2, DE LA LIG"}, {"periodo": 201503, "idRegimen": 820, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "RETRIBUCIONES POR SERVICIOS PERSONALES INDEPENDIENTES"}, {"periodo": 201503, "idRegimen": 821, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "LOCACION DE COSAS MUEBLES DEL PAIS, EFECTUADAS POR LOCADORES DEL EXTERIOR"}, {"periodo": 201507, "idRegimen": 860, "idImpuesto": 218, "tipoRegimen": "PAGO UNICO Y DEFINITIVO", "descripcionRegimen": "DIV. O UTILIDADES EN DINERO O ESPECIE - EXCEPTO ACCIONES O CUOTAS PARTES - LEY 26893"}, {"periodo": 201503, "idRegimen": 894, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSPORTE INTERNACIONAL - OPERACIONES CON CONTENEDORES"}, {"periodo": 201503, "idRegimen": 897, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSPORTE INTERNACIONAL - ARMADORES EXTRANJEROS - FLETAMENTOS A TIEMPO"}, {"periodo": 201503, "idRegimen": 901, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSMISIONES DE RADIO Y TELEVISION EMITIDAS DESDE EL EXTERIOR, SERVICIO DE TELEX, TELEFACSIMIL O SIMILARES, TRANSMITIDOS DESDE EL EXTERIOR Y TODO OTRO MEDIO EXTRANJERO DE PROYECCION, REPRODUCCION, TRANSMISION O DIFUSION DE IMAGENES O SONIDO"}, {"periodo": 201503, "idRegimen": 902, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSFERENCIA DE TECNOLOGIA - ASISTENCIA TECNICA, SERVICIOS DE INGENIERIA O CONSULTORIA NO OBTENIBLES EN EL PAIS INCLUIDAS EN EL INCISO A) PUNTO 1, DEL ART.93 DE LA LIG EXCEPTO SOFTWARE"}, {"periodo": 201503, "idRegimen": 903, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "TRANSFERENCIA DE TECNOLOGIA - MARCAS Y PATANTES Y DEMAS PRESENTACIONES DE TECNOLOGIA DEL INCISO A) PUNTO 2. DEL ART. 93 DE LA LIG -EXCEPTO SOFTWARE"}, {"periodo": 201503, "idRegimen": 904, "idImpuesto": 218, "tipoRegimen": "RETENCION", "descripcionRegimen": "INTERESES POR PRESTAMOS OBTENIDOS EN EL EXTERIOR - ART. 93 INCISO C) PUNTO 1, DE LA LIG"}, {"periodo": 200005, "idRegimen": 740, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "EMPRESAS CONSTRUCTORAS"}, {"periodo": 200005, "idRegimen": 742, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "EMPRESAS DE SERVICIOS EVENTUALES"}, {"periodo": 200312, "idRegimen": 748, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "RETENCIÓN DE PRESTADORES DE SERVICIOS DE LIMPIEZA DE INMUEBLES"}, {"periodo": 200502, "idRegimen": 754, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "RETENCION CONTRIBUCIONES PATRONALES PRESTACION SERVICIOS DE INVESTIGACIÓN Y SEGURIDAD"}, {"periodo": 201007, "idRegimen": 755, "idImpuesto": 353, "tipoRegimen": "RETENCION", "descripcionRegimen": "RETENCIÓN GENERAL DE CONTRIBUCIONES"}, {"periodo": 200808, "idRegimen": 254, "idImpuesto": 767, "tipoRegimen": "PERCEPCION", "descripcionRegimen": "PERCEPCIÓN RG 2459-CANJE GRANOS-SUJETO EN ESTADO 2 EN EL SISTEMA DE INFORMACIÓN SIMPLIFICADO AGRÍCOLA SISA"}, {"periodo": 200808, "idRegimen": 255, "idImpuesto": 767, "tipoRegimen": "PERCEPCION", "descripcionRegimen": "PERCEPCIÓN RG 2459-CANJE GRANOS-SUJETO EN ESTADO 3 EN EL SISTEMA DE INFORMACIÓN SIMPLIFICADO AGRÍCOLA SISA"}, {"periodo": 200001, "idRegimen": 493, "idImpuesto": 767, "tipoRegimen": "PERCEPCION", "descripcionRegimen": "REG.PER.AL VALOR AGREGADO - EMPRESAS PROVEEDORAS."}, {"periodo": 200904, "idRegimen": 777, "idImpuesto": 767, "tipoRegimen": "RETENCION", "descripcionRegimen": "IVA -RÉGIMEN DE RETENCIÓN A SUJETOS ADHERIDOS AL RÉGIMEN SIMPLIFICADO PARA PEQUEÑOS CONTRIBUYENTES."}, {"periodo": 201706, "idRegimen": 160, "idImpuesto": 787, "tipoRegimen": "RETENCION", "descripcionRegimen": "RENTAS DEL TRABAJO PERSONAL BAJO RELACIÓN DE DEPENDENCIA Y OTROS"}, {"periodo": 20070101, "idRegimen": 68, "idImpuesto": 103, "descripcionRegimen": "PARTICIPACIONES SOCIETARIAS"}, {"periodo": 20080603, "idRegimen": 71, "idImpuesto": 103, "descripcionRegimen": "CITI - VENTAS"}, {"periodo": 20050101, "idRegimen": 72, "idImpuesto": 103, "descripcionRegimen": "CITI - COMPRAS"}, {"periodo": 20040701, "idRegimen": 74, "idImpuesto": 103, "descripcionRegimen": "RANCHO - PRODUCTORES"}, {"periodo": 20100101, "idRegimen": 216, "idImpuesto": 103, "descripcionRegimen": "TARJETAS DE CREDITO"}, {"periodo": 20091201, "idRegimen": 255, "idImpuesto": 103, "descripcionRegimen": "PRESENTACION DE ESTADOS CONTABLES EN FORMATO PDF"}], "impuesto": [{"periodo": 198005, "idImpuesto": 10, "descripcionImpuesto": "GANANCIAS SOCIEDADES"}, {"periodo": 198903, "idImpuesto": 30, "descripcionImpuesto": "IVA"}, {"periodo": 200407, "idImpuesto": 103, "descripcionImpuesto": "REGIMENES DE INFORMACIÓN"}, {"periodo": 199206, "idImpuesto": 181, "descripcionImpuesto": "COMB LIQ L 23966 NAFTAS"}, {"periodo": 200305, "idImpuesto": 211, "descripcionImpuesto": "BP-ACCIONES O PARTICIPACIONES"}, {"periodo": 202002, "idImpuesto": 216, "descripcionImpuesto": "SIRE -  IVA"}, {"periodo": 200001, "idImpuesto": 217, "descripcionImpuesto": "SICORE-IMPTO.A LAS GANANCIAS"}, {"periodo": 201503, "idImpuesto": 218, "descripcionImpuesto": "IMP.A LAS GAN.- BENEF.DEL EXT."}, {"periodo": 200201, "idImpuesto": 228, "descripcionImpuesto": "FONDO HIDRIC DE INFRAESTRUCTUR"}, {"periodo": 200205, "idImpuesto": 229, "descripcionImpuesto": "RECARGO SOBRE EL GAS NATURAL"}, {"periodo": 200701, "idImpuesto": 240, "descripcionImpuesto": "NAFTA FONDO HIDRICO DE INFR."}, {"periodo": 192206, "idImpuesto": 301, "descripcionImpuesto": "EMPLEADOR-APORTES SEG. SOCIAL"}, {"periodo": 200005, "idImpuesto": 353, "descripcionImpuesto": "RETENCIONES CONTRIB.SEG.SOCIAL"}, {"periodo": 199807, "idImpuesto": 377, "descripcionImpuesto": "COM LIQ L.23966/24699 ART 2DOA"}, {"periodo": 199807, "idImpuesto": 395, "descripcionImpuesto": "COMB LIQ L 23966/24699 ART 2 B"}, {"periodo": 200506, "idImpuesto": 398, "descripcionImpuesto": "IMPUESTO S/GAS OIL"}, {"periodo": 200001, "idImpuesto": 767, "descripcionImpuesto": "SICORE - RETENCIONES Y PERCEPC"}, {"periodo": 201706, "idImpuesto": 787, "descripcionImpuesto": "RET ART 79 LEY GCIAS INC A,BYC"}, {"periodo": 201803, "idImpuesto": 1018, "descripcionImpuesto": "CO2 - NAFTAS"}, {"periodo": 201803, "idImpuesto": 1019, "descripcionImpuesto": "CO2-SOLV. AGUARRAS GASOL.NAF V"}, {"periodo": 201803, "idImpuesto": 1020, "descripcionImpuesto": "CO2 - GASOIL DIESELOIL Y KEROS"}, {"periodo": 201901, "idImpuesto": 1021, "descripcionImpuesto": "DIOXIDO DE CARBONO - FUEL OIL"}, {"periodo": 201901, "idImpuesto": 1022, "descripcionImpuesto": "CO2 - COQUE PETROL Y CARB MIN"}], "actividad": [{"orden": 1, "periodo": 201401, "idActividad": 61000, "nomenclador": 883, "descripcionActividad": "EXTRACCIÓN DE PETRÓLEO CRUDO"}, {"orden": 2, "periodo": 201401, "idActividad": 62000, "nomenclador": 883, "descripcionActividad": "EXTRACCIÓN DE GAS NATURAL"}, {"orden": 13, "periodo": 201902, "idActividad": 81300, "nomenclador": 883, "descripcionActividad": "EXTRACCIÓN DE ARENAS, CANTO RODADO Y TRITURADOS PÉTREOS"}, {"orden": 3, "periodo": 201401, "idActividad": 192000, "nomenclador": 883, "descripcionActividad": "FABRICACIÓN DE PRODUCTOS DE LA REFINACIÓN DEL PETRÓLEO"}, {"orden": 6, "periodo": 201401, "idActividad": 351110, "nomenclador": 883, "descripcionActividad": "GENERACIÓN DE ENERGÍA TÉRMICA CONVENCIONAL"}, {"orden": 8, "periodo": 201401, "idActividad": 461011, "nomenclador": 883, "descripcionActividad": "VENTA AL POR MAYOR EN COMISIÓN O CONSIGNACIÓN DE CEREALES (INCLUYE ARROZ), OLEAGINOSAS Y FORRAJERAS EXCEPTO SEMILLAS"}, {"orden": 9, "periodo": 201405, "idActividad": 473000, "nomenclador": 883, "descripcionActividad": "VENTA AL POR MENOR DE COMBUSTIBLE PARA VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"}, {"orden": 10, "periodo": 201509, "idActividad": 649210, "nomenclador": 883, "descripcionActividad": "ACTIVIDADES DE CRÉDITO PARA FINANCIAR OTRAS ACTIVIDADES ECONÓMICAS"}, {"orden": 12, "periodo": 201612, "idActividad": 649999, "nomenclador": 883, "descripcionActividad": "SERVICIOS DE FINANCIACIÓN Y ACTIVIDADES FINANCIERAS N.C.P."}, {"orden": 11, "periodo": 201612, "idActividad": 661121, "nomenclador": 883, "descripcionActividad": "SERVICIOS DE MERCADOS A TÉRMINO"}, {"orden": 7, "periodo": 201401, "idActividad": 681098, "nomenclador": 883, "descripcionActividad": "SERVICIOS INMOBILIARIOS REALIZADOS POR CUENTA PROPIA, CON BIENES URBANOS PROPIOS O ARRENDADOS N.C.P."}, {"orden": 5, "periodo": 201401, "idActividad": 681099, "nomenclador": 883, "descripcionActividad": "SERVICIOS INMOBILIARIOS REALIZADOS POR CUENTA PROPIA, CON BIENES RURALES PROPIOS O ARRENDADOS N.C.P."}, {"orden": 4, "periodo": 201401, "idActividad": 682099, "nomenclador": 883, "descripcionActividad": "SERVICIOS INMOBILIARIOS REALIZADOS A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA N.C.P."}]}}',
                'created_at' => '2021-05-18 15:44:15',
                'updated_at' => '2021-05-18 15:44:15',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => NULL,
                'meli_nick' => NULL,
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'ROMERO GABRIEL',
                'number' => '20250836210',
                'inscription_id' => 5,
                'address_id' => NULL,
                'purchaser_document_id' => 26,
                'datos_generales' => NULL,
                'regimen_general' => NULL,
                'monotributo' => NULL,
                'error_constancia' => NULL,
                'contact' => NULL,
                'afip_data' => '{"metadata": {"servidor": "linux11c", "fechaHora": "2021-05-18T13:15:37.593-03:00"}, "errorConstancia": {"error": "La clave ingresada no es una CUIT", "apellido": "ROMERO GABRIEL", "idPersona": 20250836210}}',
                'created_at' => '2021-05-18 16:15:37',
                'updated_at' => '2021-05-18 16:15:37',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => NULL,
                'meli_nick' => NULL,
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'MERAYO ALFREDO ADRIAN',
                'number' => '20261694086',
                'inscription_id' => 1,
                'address_id' => NULL,
                'purchaser_document_id' => 25,
                'datos_generales' => '{"nombre": "ALFREDO ADRIAN", "apellido": "MERAYO", "idPersona": 20261694086, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1708", "direccion": "AV. JUAN MANUEL DE ROSAS 161", "localidad": "MORON", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}',
                'regimen_general' => '{"impuesto": [{"periodo": 200209, "idImpuesto": 11, "descripcionImpuesto": "GANANCIAS PERSONAS FISICAS"}, {"periodo": 200209, "idImpuesto": 30, "descripcionImpuesto": "IVA"}, {"periodo": 200606, "idImpuesto": 301, "descripcionImpuesto": "EMPLEADOR-APORTES SEG. SOCIAL"}, {"periodo": 200209, "idImpuesto": 308, "descripcionImpuesto": "APORTES SEG.SOCIAL AUTONOMOS"}], "actividad": {"orden": 1, "periodo": 201311, "idActividad": 452401, "nomenclador": 883, "descripcionActividad": "REPARACIONES ELÉCTRICAS DEL TABLERO E INSTRUMENTAL, REPARACIÓN Y RECARGA DE BATERÍAS, INSTALACIÓN DE ALARMAS, RADIOS, SISTEMAS DE CLIMATIZACIÓN"}, "categoriaAutonomo": {"periodo": 200703, "idImpuesto": 308, "idCategoria": 302, "descripcionCategoria": "T3 CAT II INGRESOS DESDE $25.001"}}',
                'monotributo' => NULL,
                'error_constancia' => NULL,
                'contact' => NULL,
                'afip_data' => '{"metadata": {"servidor": "linux11f", "fechaHora": "2021-05-19T15:27:01.992-03:00"}, "datosGenerales": {"nombre": "ALFREDO ADRIAN", "apellido": "MERAYO", "idPersona": 20261694086, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1708", "direccion": "AV. JUAN MANUEL DE ROSAS 161", "localidad": "MORON", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}, "datosRegimenGeneral": {"impuesto": [{"periodo": 200209, "idImpuesto": 11, "descripcionImpuesto": "GANANCIAS PERSONAS FISICAS"}, {"periodo": 200209, "idImpuesto": 30, "descripcionImpuesto": "IVA"}, {"periodo": 200606, "idImpuesto": 301, "descripcionImpuesto": "EMPLEADOR-APORTES SEG. SOCIAL"}, {"periodo": 200209, "idImpuesto": 308, "descripcionImpuesto": "APORTES SEG.SOCIAL AUTONOMOS"}], "actividad": {"orden": 1, "periodo": 201311, "idActividad": 452401, "nomenclador": 883, "descripcionActividad": "REPARACIONES ELÉCTRICAS DEL TABLERO E INSTRUMENTAL, REPARACIÓN Y RECARGA DE BATERÍAS, INSTALACIÓN DE ALARMAS, RADIOS, SISTEMAS DE CLIMATIZACIÓN"}, "categoriaAutonomo": {"periodo": 200703, "idImpuesto": 308, "idCategoria": 302, "descripcionCategoria": "T3 CAT II INGRESOS DESDE $25.001"}}}',
                'created_at' => '2021-05-19 18:27:20',
                'updated_at' => '2021-05-19 18:27:20',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => NULL,
                'meli_nick' => NULL,
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            10 => 
            array (
                'id' => 27,
                'name' => NULL,
                'number' => NULL,
                'inscription_id' => NULL,
                'address_id' => NULL,
                'purchaser_document_id' => NULL,
                'datos_generales' => NULL,
                'regimen_general' => NULL,
                'monotributo' => NULL,
                'error_constancia' => NULL,
                'contact' => NULL,
                'afip_data' => NULL,
                'created_at' => '2021-05-26 16:19:01',
                'updated_at' => '2021-05-26 16:19:01',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => '423831121',
                'meli_nick' => 'TESTWCBNLWU3',
                'has_afip_data' => 0,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
            11 => 
            array (
                'id' => 28,
                'name' => 'MONZON ANDREA VANESA',
                'number' => '23290244234',
                'inscription_id' => 6,
                'address_id' => 14,
                'purchaser_document_id' => 25,
                'datos_generales' => '{"nombre": "ANDREA VANESA", "apellido": "MONZON", "idPersona": 23290244234, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1888", "direccion": "PEDRO MORAN 1264", "localidad": "FLORENCIO VARELA", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}',
                'regimen_general' => NULL,
                'monotributo' => '{"impuesto": {"periodo": 201005, "idImpuesto": 20, "descripcionImpuesto": "MONOTRIBUTO"}, "categoriaMonotributo": {"periodo": 202102, "idImpuesto": 20, "idCategoria": 36, "descripcionCategoria": "B LOCACIONES DE SERVICIO"}, "actividadMonotributista": {"orden": 1, "periodo": 201311, "idActividad": 949990, "nomenclador": 883, "descripcionActividad": "SERVICIOS DE ASOCIACIONES N.C.P."}}',
                'error_constancia' => NULL,
                'contact' => NULL,
                'afip_data' => '{"metadata": {"servidor": "linux11f", "fechaHora": "2021-06-08T14:56:35.427-03:00"}, "datosGenerales": {"nombre": "ANDREA VANESA", "apellido": "MONZON", "idPersona": 23290244234, "mesCierre": 12, "tipoClave": "CUIT", "estadoClave": "ACTIVO", "tipoPersona": "FISICA", "domicilioFiscal": {"codPostal": "1888", "direccion": "PEDRO MORAN 1264", "localidad": "FLORENCIO VARELA", "idProvincia": 1, "tipoDomicilio": "FISCAL", "descripcionProvincia": "BUENOS AIRES"}}, "datosMonotributo": {"impuesto": {"periodo": 201005, "idImpuesto": 20, "descripcionImpuesto": "MONOTRIBUTO"}, "categoriaMonotributo": {"periodo": 202102, "idImpuesto": 20, "idCategoria": 36, "descripcionCategoria": "B LOCACIONES DE SERVICIO"}, "actividadMonotributista": {"orden": 1, "periodo": 201311, "idActividad": 949990, "nomenclador": 883, "descripcionActividad": "SERVICIOS DE ASOCIACIONES N.C.P."}}}',
                'created_at' => '2021-06-08 17:56:35',
                'updated_at' => '2021-06-08 17:56:35',
                'cell_phone' => NULL,
                'phone_1' => NULL,
                'phone_2' => NULL,
                'phone_3' => NULL,
                'email' => NULL,
                'others' => NULL,
                'status_id' => 1,
                'meli_id' => NULL,
                'meli_nick' => NULL,
                'has_afip_data' => 1,
                'pay_condition' => NULL,
                'customer_type_id' => 1,
                'accounting_account_parent_id' => 16,
                'accounting_account_child_id' => NULL,
            ),
        ));
        
        
    }
}