INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (7,'BANCO DE GALICIA Y BUENOS AIRES S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (11,'BANCO DE LA NACION ARGENTINA');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (14,'BANCO DE LA PROVINCIA DE BUENOS AIRES');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (15,'INDUSTRIAL AND COMMERCIAL BANK OF CHINA');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (16,'CITIBANK N.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (17,'BBVA BANCO FRANCES S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (18,'THE BANK OF TOKYO-MITSUBISHI UFJ, LTD.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (20,'BANCO DE LA PROVINCIA DE CORDOBA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (27,'BANCO SUPERVIELLE S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (29,'BANCO DE LA CIUDAD DE BUENOS AIRES');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (34,'BANCO PATAGONIA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44,'BANCO HIPOTECARIO S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (45,'BANCO DE SAN JUAN S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (60,'BANCO DEL TUCUMAN S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (65,'BANCO MUNICIPAL DE ROSARIO');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (72,'BANCO SANTANDER RIO S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (83,'BANCO DEL CHUBUT S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (86,'BANCO DE SANTA CRUZ S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (93,'BANCO DE LA PAMPA SOCIEDAD DE ECONOMÍA M');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (94,'BANCO DE CORRIENTES S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (97,'BANCO PROVINCIA DEL NEUQUÉN SOCIEDAD ANÓ');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (147,'BANCO INTERFINANZAS S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (150,'HSBC BANK ARGENTINA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (165,'JPMORGAN CHASE BANK, NATIONAL ASSOCIATIO');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (191,'BANCO CREDICOOP COOPERATIVO LIMITADO');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (198,'BANCO DE VALORES S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (247,'BANCO ROELA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (254,'BANCO MARIVA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (259,'BANCO ITAU ARGENTINA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (262,'BANK OF AMERICA, NATIONAL ASSOCIATION');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (266,'BNP PARIBAS');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (268,'BANCO PROVINCIA DE TIERRA DEL FUEGO');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (269,'BANCO DE LA REPUBLICA ORIENTAL DEL URUGU');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (277,'BANCO SAENZ S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (281,'BANCO MERIDIAN S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (285,'BANCO MACRO S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (299,'BANCO COMAFI SOCIEDAD ANONIMA');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (300,'BANCO DE INVERSION Y COMERCIO EXTERIOR S');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (301,'BANCO PIANO S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (303,'BANCO FINANSUR S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (305,'BANCO JULIO SOCIEDAD ANONIMA');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (309,'BANCO RIOJA SOCIEDAD ANONIMA UNIPERSONAL');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (310,'BANCO DEL SOL S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (311,'NUEVO BANCO DEL CHACO S. A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (312,'BANCO VOII S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (315,'BANCO DE FORMOSA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (319,'BANCO CMF S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (321,'BANCO DE SANTIAGO DEL ESTERO S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (322,'BANCO INDUSTRIAL S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (330,'NUEVO BANCO DE SANTA FE SOCIEDAD ANONIMA');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (331,'BANCO CETELEM ARGENTINA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (332,'BANCO DE SERVICIOS FINANCIEROS S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (336,'BANCO BRADESCO ARGENTINA S.A.U.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (338,'BANCO DE SERVICIOS Y TRANSACCIONES S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (339,'RCI BANQUE S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (340,'BACS BANCO DE CREDITO Y SECURITIZACION S');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (341,'BANCO MASVENTAS S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (386,'NUEVO BANCO DE ENTRE RÍOS S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (389,'BANCO COLUMBIA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (426,'BANCO BICA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (431,'BANCO COINAG S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (432,'BANCO DE COMERCIO S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44059,'FORD CREDIT COMPAÑIA FINANCIERA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44077,'COMPAÑIA FINANCIERA ARGENTINA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44088,'VOLKWAGEN FINANCIAL SERVICES CIA.FIN.S.A');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44090,'CORDIAL COMPAÑÍA FINANCIERA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44092,'FCA COMPAÑIA FINANCIERA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44093,'GPAT COMPAÑIA FINANCIERA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44094,'MERCEDES-BENZ COMPAÑÍA FINANCIERA ARGENT');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44095,'ROMBO COMPAÑÍA FINANCIERA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44096,'JOHN DEERE CREDIT COMPAÑÍA FINANCIERA S.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44098,'PSA FINANCE ARGENTINA COMPAÑÍA FINANCIER');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44099,'TOYOTA COMPAÑÍA FINANCIERA DE ARGENTINA');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (44100,'FINANDINO COMPAÑIA FINANCIERA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (45056,'MONTEMAR COMPAÑIA FINANCIERA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (45072,'MULTIFINANZAS COMPAÑIA FINANCIERA S.A.');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (65203,'CAJA DE CREDITO \"CUENCA\" COOPERATIVA LIM');
INSERT INTO `misistema`.`banks` (`code`,`name`) VALUES (99999,'MERCADO PAGO');



