INSERT INTO `misistema`.`states`(`afip_code`, `name`, `codigo31662`) VALUES
(0, 'CABA','AR-C'),
(1, 'Buenos Aires','AR-B'),
(2, 'Catamarca','AR-K'),
(3, 'Córdoba','AR-X'),
(4, 'Corrientes','AR-W'),
(5, 'Entre Ríos','AR-E'),
(6, 'Jujuy','AR-Y'),
(7, 'Mendoza','AR-M'),
(8, 'La Rioja','AR-F'),
(9, 'Salta','AR-A'),
(10, 'San Juan','AR-J'),
(11, 'San Luis','AR-D'),
(12, 'Santa Fe','AR-S'),
(13, 'Santiago del Estero','AR-G'),
(14, 'Tucumán','AR-T'),
(16, 'Chaco','AR-H'),
(17, 'Chubut','AR-U'),
(18, 'Formosa','AR-P'),
(19, 'Misiones','AR-N'),
(20, 'Neuquén','AR-Q'),
(21, 'La Pampa','AR-L'),
(22, 'Río Negro','AR-R'),
(23, 'Santa Cruz','AR-Z'),
(24, 'Tierra del Fuego','AR-V');
